// ═══════════════════════════════════════════════════════
// ROOTS & ROARS — Species Database
// Using Wikimedia Commons & Unsplash for real photos
// ═══════════════════════════════════════════════════════

const SPECIES = {
  tiger: {
    id: 'tiger', icon: '🐯', name: 'Bengal Tiger', sci: 'Panthera tigris tigris',
    status: 'EN', statusLabel: 'Endangered', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tiger_in_Ranthambhore.jpg/1280px-Tiger_in_Ranthambhore.jpg',
    heroGrad: 'linear-gradient(140deg,#1a0e05,#3a1a08,#7a4520)',
    iucn: 'EN', popTrend: 'Increasing', popNum: '~3,726–5,578 wild',
    popWhere: 'India (75%+), Bangladesh, Nepal, Bhutan',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Carnivora', Family:'Felidae', Genus:'Panthera', Species:'P. t. tigris' },
    stats: [
      { l:'Population', v:'~4,500', u:'wild' },
      { l:'Lifespan', v:'10–15', u:'years' },
      { l:'Top Speed', v:'65', u:'km/h' },
      { l:'Weight', v:'220', u:'kg avg' },
      { l:'Length', v:'3.1', u:'m avg' }
    ],
    about: `The Bengal Tiger is India's national animal and its apex predator — a solitary hunter of extraordinary physical power and stealth. Each tiger carries a stripe pattern as individual as a human fingerprint, which forms the basis of India's entire camera-trap census for Project Tiger. Once numbering over 100,000 across Asia, rampant hunting and habitat loss reduced them to fewer than 2,000 by 1973. India's Project Tiger, launched that year, has reversed the decline: India now shelters over 75% of all wild tigers on Earth.`,
    diet: [
      { label:'Sambar Deer', pct:45, color:'#3d7a4f' },
      { label:'Chital', pct:25, color:'#52a669' },
      { label:'Wild Boar', pct:18, color:'#c8922a' },
      { label:'Gaur', pct:8, color:'#e8b04a' },
      { label:'Other', pct:4, color:'#555' }
    ],
    habitat: 'Dense subtropical and tropical forests, grasslands, and mangroves. Key habitats include Sundarbans mangroves (Bengal), sal forests of Corbett and Kanha, and the dry deciduous forests of Panna and Ranthambore.',
    behavior: 'Solitary and highly territorial. Males maintain ranges of 60–100 km², females 20–60 km². They are primarily nocturnal hunters but may hunt during the day. Tigers are strong swimmers and readily enter water to cool down or cross rivers.',
    mating: [{ l:'Season', v:'Year-round' }, { l:'Gestation', v:'103–105 days' }, { l:'Litter size', v:'2–4 cubs' }, { l:'Independence', v:'18–28 months' }],
    funFacts: [
      { icon:'👁️', text:'A tiger\'s <strong>roar can be heard 3 km away</strong> — and its infrasound is felt before it is heard, paralysing smaller prey.' },
      { icon:'🏊', text:'Tigers are <strong>excellent swimmers</strong> and have been recorded crossing rivers 8 km wide in the Sundarbans.' },
      { icon:'🌙', text:'A tiger\'s <strong>night vision is 6× better</strong> than a human\'s. Tapetum lucidum behind the retina reflects light, amplifying what\'s available.' },
      { icon:'💪', text:'A single swipe of a tiger\'s paw can <strong>break a bear\'s jaw</strong>. Adult males weigh up to 250 kg of pure muscle.' },
    ],
    attrs: [
      { lbl:'Nocturnal', cls:'#374151' }, { lbl:'Carnivore', cls:'#7f1d1d' }, { lbl:'Apex Predator', cls:'#6d28d9' },
      { lbl:'Solitary', cls:'#14532d' }, { lbl:'Territorial', cls:'#92400e' }, { lbl:'Viviparous', cls:'#1e3a5f' },
    ],
    threats: ['Habitat loss and fragmentation from agriculture', 'Poaching for skin, bones and traditional medicine', 'Human–wildlife conflict as forests shrink', 'Prey depletion by bushmeat hunting', 'Roads and railways cutting through tiger corridors'],
    range: ['Sundarbans, West Bengal', 'Madhya Pradesh (Kanha, Pench, Bandhavgarh)', 'Rajasthan (Ranthambore, Sariska)', 'Uttarakhand (Corbett)', 'Assam & Northeast India'],
    related: ['elephant', 'snowleopard', 'gaur', 'chital'],
    sizeH: 100, sizeType: 'quadruped', sound: 'tiger',
  },

  elephant: {
    id: 'elephant', icon: '🐘', name: 'Asian Elephant', sci: 'Elephas maximus',
    status: 'EN', statusLabel: 'Endangered', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Above_Gotland_-_Asian_elephant_at_Pinnawala_Elephant_Orphanage.jpg/1280px-Above_Gotland_-_Asian_elephant_at_Pinnawala_Elephant_Orphanage.jpg',
    heroGrad: 'linear-gradient(140deg,#0a0e10,#1a2830,#3a5060)',
    iucn: 'EN', popTrend: 'Decreasing', popNum: '~50,000 wild',
    popWhere: 'India (60%), Sri Lanka, Southeast Asia',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Proboscidea', Family:'Elephantidae', Genus:'Elephas', Species:'E. maximus' },
    stats: [
      { l:'Population', v:'~50,000', u:'wild' },
      { l:'Lifespan', v:'60–70', u:'years' },
      { l:'Top Speed', v:'25', u:'km/h' },
      { l:'Weight', v:'4,000', u:'kg avg' },
      { l:'Height', v:'2.7', u:'m shoulder' }
    ],
    about: 'The Asian Elephant is the largest land animal in Asia. Highly intelligent and deeply social, herds are led by matriarchs — the oldest, wisest female — whose memory and experience is vital for herd survival. They communicate through infrasound vibrations that travel through the earth, detectable 30+ km away through feet and trunk. India holds approximately 60% of all wild Asian elephants.',
    diet: [
      { label:'Grass', pct:50, color:'#3d7a4f' },
      { label:'Bark & leaves', pct:30, color:'#52a669' },
      { label:'Fruits', pct:14, color:'#c8922a' },
      { label:'Roots', pct:6, color:'#e8b04a' }
    ],
    habitat: 'Forests, grasslands, scrublands and agricultural borders across South and Southeast Asia. Key Indian habitats: Nilgiri Biosphere (Tamil Nadu/Kerala/Karnataka), Corbett–Rajaji corridor, and the elephant ranges of Assam and Arunachal.',
    behavior: 'Deeply social. Herds of 6–20 females and calves roam together. Bulls are typically solitary or in loose bachelor groups, entering musth periodically — a surge of testosterone. Elephants mourn their dead and exhibit empathy.',
    mating: [{ l:'Season', v:'Year-round' }, { l:'Gestation', v:'22 months' }, { l:'Birth weight', v:'~90 kg' }, { l:'Weaning', v:'4–5 years' }],
    funFacts: [
      { icon:'👂', text:'Elephant ears <strong>radiate heat like a radiator</strong>, functioning as the animal\'s primary cooling system in India\'s heat.' },
      { icon:'🧠', text:'Elephants are <strong>one of three mammals known to pass the mirror self-recognition test</strong> — a mark of advanced self-awareness.' },
      { icon:'💧', text:'An elephant trunk contains <strong>over 150,000 muscle units</strong> and can hold 8.5 litres of water.' },
      { icon:'🦶', text:'Elephants walk <strong>on their tiptoes</strong>. Their foot pads act as natural shock absorbers, letting them move almost silently.' },
    ],
    attrs: [
      { lbl:'Diurnal', cls:'#78350f' }, { lbl:'Herbivore', cls:'#14532d' }, { lbl:'Social', cls:'#1e3a5f' },
      { lbl:'Matriarchal', cls:'#9d174d' }, { lbl:'Intelligent', cls:'#6d28d9' }, { lbl:'Migrant', cls:'#0f766e' },
    ],
    threats: ['Habitat loss to agriculture, roads and settlements', 'Human–elephant conflict causing deaths on both sides', 'Ivory and captive trade poaching', 'Fragmentation of corridors by linear infrastructure'],
    range: ['Nilgiri Biosphere (TN/Kerala/Karnataka)', 'Assam & Arunachal Pradesh', 'Corbett–Rajaji corridor (Uttarakhand)', 'Odisha elephant ranges'],
    related: ['tiger', 'rhino', 'gaur', 'chital'],
    sizeH: 270, sizeType: 'elephant', sound: 'elephant',
  },

  peacock: {
    id: 'peacock', icon: '🦚', name: 'Indian Peacock', sci: 'Pavo cristatus',
    status: 'LC', statusLabel: 'Least Concern', category: 'birds',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Indian_Peacock_DSC_0612.jpg/1280px-Indian_Peacock_DSC_0612.jpg',
    heroGrad: 'linear-gradient(140deg,#050a18,#0d1a30,#1a3055)',
    iucn: 'LC', popTrend: 'Stable', popNum: '100,000+ wild',
    popWhere: 'Indian Subcontinent — widely distributed',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Aves', Order:'Galliformes', Family:'Phasianidae', Genus:'Pavo', Species:'P. cristatus' },
    stats: [
      { l:'Population', v:'>100,000', u:'wild' },
      { l:'Lifespan', v:'15–20', u:'years' },
      { l:'Wingspan', v:'1.4', u:'m' },
      { l:'Weight', v:'4–6', u:'kg' },
      { l:'Train span', v:'1.8', u:'m' }
    ],
    about: `India's national bird, the Indian Peacock is one of the world's most spectacular animals. The "tail" — scientifically the upper tail covert feathers — can contain 200 eye-spotted feathers spanning nearly 2 metres. Peahens select mates based partly on UV reflectance patterns in these feathers that are invisible to human eyes. The quivering train display also produces infrasound below 100 Hz, transmitted through the air to attract females from afar.`,
    diet: [
      { label:'Insects', pct:35, color:'#3d7a4f' }, { label:'Seeds & grain', pct:30, color:'#52a669' },
      { label:'Reptiles', pct:20, color:'#c8922a' }, { label:'Berries', pct:15, color:'#e8b04a' }
    ],
    habitat: 'Open forests, agricultural land, scrub forest, and village margins across the Indian subcontinent. Peacocks prefer areas with tall trees for roosting and open ground for foraging. They thrive near water.',
    behavior: 'Polygamous and diurnal. Males perform elaborate courtship displays — fanning and vibrating the train — during the breeding season (February–May). Outside breeding, peacocks may form loose mixed-sex groups. They roost high in trees overnight for safety.',
    mating: [{ l:'Season', v:'Feb–May' }, { l:'Clutch size', v:'4–8 eggs' }, { l:'Incubation', v:'27–30 days' }, { l:'Chick type', v:'Precocial' }],
    funFacts: [
      { icon:'🎵', text:'The peacock\'s train display produces <strong>infrasound below 100 Hz</strong>, imperceptible to humans but felt by peahens across a wide area.' },
      { icon:'🔵', text:'The blue-green iridescence is <strong>structural colour</strong> — no blue pigment exists. Microscopic crystal lattices diffract light.' },
      { icon:'👁️', text:'Peahens choose mates partly on <strong>UV reflectance patterns</strong> invisible to humans, visible only to birds with tetrachromatic vision.' },
      { icon:'🐍', text:'Peacocks are <strong>natural predators of cobras</strong> and help control snake populations around Indian villages.' },
    ],
    attrs: [{ lbl:'Diurnal', cls:'#78350f' }, { lbl:'Omnivore', cls:'#c2410c' }, { lbl:'Oviparous', cls:'#0f766e' }, { lbl:'Polygynous', cls:'#9d174d' }],
    threats: ['Poaching for feathers (despite legal protection)', 'Habitat degradation from agriculture', 'Pesticide poisoning affecting food supply'],
    range: ['Pan-India (below 1,800m)', 'Sri Lanka', 'Pakistan (Sindh province)'],
    related: ['tiger', 'elephant', 'gharial', 'chital'],
    sizeH: 90, sizeType: 'bird', sound: 'peacock',
  },

  snowleopard: {
    id: 'snowleopard', icon: '🐆', name: 'Snow Leopard', sci: 'Panthera uncia',
    status: 'VU', statusLabel: 'Vulnerable', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Schneeleopard-schneeleopard.jpg/1280px-Schneeleopard-schneeleopard.jpg',
    heroGrad: 'linear-gradient(140deg,#0a0e14,#1a2030,#2a3845)',
    iucn: 'VU', popTrend: 'Decreasing', popNum: '4,000–6,500 wild',
    popWhere: 'India (Ladakh, HP, Uttarakhand), China, Central Asia',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Carnivora', Family:'Felidae', Genus:'Panthera', Species:'P. uncia' },
    stats: [
      { l:'Population', v:'4,000–6,500', u:'wild' },
      { l:'Lifespan', v:'10–12', u:'years' },
      { l:'Top Speed', v:'55', u:'km/h' },
      { l:'Weight', v:'38', u:'kg avg' },
      { l:'Altitude', v:'3,000–5,500', u:'m' }
    ],
    about: 'The "Ghost of the Mountains" — the Snow Leopard is so elusive that sighting one in the wild is among the rarest wildlife experiences on Earth. Perfectly adapted to extreme cold with a thick smoke-grey spotted coat, large padded paws acting as natural snowshoes, and a tail nearly as long as the body. India\'s Ladakh region holds some of the highest densities of snow leopards anywhere.',
    diet: [
      { label:'Bharal (Blue sheep)', pct:55, color:'#3d7a4f' }, { label:'Himalayan tahr', pct:20, color:'#52a669' },
      { label:'Rodents', pct:15, color:'#c8922a' }, { label:'Livestock', pct:10, color:'#e8b04a' }
    ],
    habitat: 'Alpine and subalpine zones from 3,000 to 5,500 metres. Rocky ridges, cliff faces, and mountain passes in the Himalayas. Uses rugged terrain for both hunting and shelter. Found in Hemis National Park (Ladakh) in high densities.',
    behavior: 'Solitary and highly crepuscular — most active at dawn and dusk. Does not roar like other big cats but produces a unique "chuff" and moan. Marks territories with scrapes and spray.',
    mating: [{ l:'Season', v:'Jan–Mar' }, { l:'Gestation', v:'93–110 days' }, { l:'Litter size', v:'1–5 cubs' }, { l:'Independence', v:'18–22 months' }],
    funFacts: [
      { icon:'❄️', text:'Snow leopards have <strong>the longest tail of any big cat</strong> — up to 90 cm — which they wrap around their face like a scarf to warm the air they breathe.' },
      { icon:'👻', text:'So rare and elusive, snow leopards are called the <strong>"Ghost of the Mountains."</strong> Some local communities have never seen one despite living nearby for generations.' },
      { icon:'🦶', text:'Snow leopard paws are <strong>the size of dinner plates</strong> relative to the body, functioning as natural snowshoes on steep, icy terrain.' },
      { icon:'🔇', text:'Unlike lions and tigers, snow leopards <strong>cannot roar</strong>. Their cartilaginous hyoid bone only allows purrs, chuffs, and a haunting moan.' },
    ],
    attrs: [{ lbl:'Crepuscular', cls:'#374151' }, { lbl:'Carnivore', cls:'#7f1d1d' }, { lbl:'Solitary', cls:'#14532d' }, { lbl:'Apex Predator', cls:'#6d28d9' }],
    threats: ['Retaliatory killing by herders after livestock losses', 'Poaching for bones and fur', 'Loss of prey species from hunting', 'Climate change reducing snow cover'],
    range: ['Ladakh (highest density in India)', 'Himachal Pradesh (Spiti, Kinnaur)', 'Uttarakhand (Gangotri, Nanda Devi)', 'Sikkim & Arunachal Pradesh'],
    related: ['tiger', 'elephant', 'gaur', 'chital'],
    sizeH: 60, sizeType: 'quadruped', sound: 'snowleopard',
  },

  gharial: {
    id: 'gharial', icon: '🐊', name: 'Gharial', sci: 'Gavialis gangeticus',
    status: 'CR', statusLabel: 'Critically Endangered', category: 'reptiles',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Female_gharial_%28Gavialis_gangeticus%29.jpg/1280px-Female_gharial_%28Gavialis_gangeticus%29.jpg',
    heroGrad: 'linear-gradient(140deg,#05100a,#0a2015,#154025)',
    iucn: 'CR', popTrend: 'Decreasing', popNum: '~650 wild',
    popWhere: 'India (Chambal, Ghaghra, Gandak rivers), Nepal',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Reptilia', Order:'Crocodilia', Family:'Gavialidae', Genus:'Gavialis', Species:'G. gangeticus' },
    stats: [
      { l:'Population', v:'~650', u:'wild' },
      { l:'Lifespan', v:'40–60', u:'years' },
      { l:'Weight', v:'180', u:'kg avg' },
      { l:'Length', v:'4–6', u:'m' },
      { l:'Teeth', v:'100+', u:'sharp' }
    ],
    about: 'One of the world\'s longest crocodilians and most critically endangered reptiles. The gharial\'s narrow, elongated snout is perfectly shaped for catching fish with a lightning-fast sideways snap — its exclusive prey. The adult male develops a distinctive bulbous "ghara" (earthen pot) at the snout tip, used for vocalisation and display. Once found across all major Indian river systems, it now survives in a handful of rivers.',
    diet: [{ label:'Fish', pct:95, color:'#3a7fa8' }, { label:'Invertebrates', pct:5, color:'#3d7a4f' }],
    habitat: 'Deep, fast-flowing rivers with clean water, sandy banks for nesting, and large sand bars for basking. The National Chambal Sanctuary holds the last significant wild population.',
    behavior: 'Highly aquatic — unlike most crocodilians, gharials rarely move on land. They bask extensively in the sun. Males hold territories along the riverbank.',
    mating: [{ l:'Season', v:'Nov–Feb' }, { l:'Clutch size', v:'30–60 eggs' }, { l:'Incubation', v:'71–93 days' }, { l:'Nest type', v:'Hole in sand' }],
    funFacts: [
      { icon:'🐟', text:'Gharials\' teeth <strong>point outward</strong> — perfect for catching slippery fish, but useless for attacking large mammals. They are <strong>completely harmless to humans</strong>.' },
      { icon:'🎩', text:'The male\'s "ghara" is <strong>a hollow nasal protrusion</strong> that amplifies hisses and buzzes, and creates bubbles during mating displays.' },
      { icon:'📦', text:'Gharials were once found in 20 rivers across India. Today, <strong>95% of the wild population lives in just one river</strong> — the Chambal.' },
      { icon:'🍳', text:'Young gharials communicate by <strong>chirping and humming</strong>. The male guards the nest — the only paternal croc species behaviour.' },
    ],
    attrs: [{ lbl:'Piscivore', cls:'#0369a1' }, { lbl:'Aquatic', cls:'#1e3a5f' }, { lbl:'Oviparous', cls:'#0f766e' }, { lbl:'Carnivore', cls:'#7f1d1d' }],
    threats: ['Sand mining destroying nesting beaches', 'Fishing nets causing drowning entanglement', 'Dam construction fragmenting river habitats', 'Irrigation abstraction reducing river flow'],
    range: ['National Chambal Sanctuary (Rajasthan/MP/UP)', 'Girwa River, Katerniaghat (UP)', 'Gandak River (Bihar/Nepal)'],
    related: ['kingcobra', 'tiger', 'elephant', 'peacock'],
    sizeH: 85, sizeType: 'croc', sound: 'gharial',
  },

  kingcobra: {
    id: 'kingcobra', icon: '🐍', name: 'King Cobra', sci: 'Ophiophagus hannah',
    status: 'VU', statusLabel: 'Vulnerable', category: 'reptiles',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Ophiophagus_hannah_in_Kaeng_Krachan.jpg/1280px-Ophiophagus_hannah_in_Kaeng_Krachan.jpg',
    heroGrad: 'linear-gradient(140deg,#0a0e05,#1a2010,#2a3818)',
    iucn: 'VU', popTrend: 'Decreasing', popNum: 'Unknown (declining)',
    popWhere: 'India (Western Ghats, Assam, Andamans), SE Asia',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Reptilia', Order:'Squamata', Family:'Elapidae', Genus:'Ophiophagus', Species:'O. hannah' },
    stats: [
      { l:'Length', v:'3–5.5', u:'m' },
      { l:'Lifespan', v:'17–20', u:'years' },
      { l:'Venom yield', v:'~7 ml', u:'per bite' },
      { l:'Hood width', v:'~30', u:'cm' },
      { l:'Territory', v:'2.4', u:'km²' }
    ],
    about: 'The world\'s longest venomous snake, reaching nearly 5.5 metres. "Ophiophagus" literally means "snake-eater" — the King Cobra feeds almost exclusively on other snakes, including large pythons. It is the only snake known to build a nest and guard its eggs and hatchlings until hatching. Its distinctive hood, haunting "growl", and upright defensive posture make it one of India\'s most iconic and feared species.',
    diet: [{ label:'Other snakes', pct:85, color:'#3d7a4f' }, { label:'Monitor lizards', pct:10, color:'#52a669' }, { label:'Small mammals', pct:5, color:'#c8922a' }],
    habitat: 'Dense highland forests, bamboo thickets, and mangroves in the Western Ghats, Assam, and the Andaman Islands. Prefers areas near water. Home ranges are large — up to 2.4 km² for a single individual.',
    behavior: 'Generally shy and avoids humans, but becomes highly defensive when cornered. Can rear up to 1.8 metres off the ground. The hood is formed by elongated ribs behind the head, spread as a warning display.',
    mating: [{ l:'Season', v:'Jan–Mar' }, { l:'Clutch size', v:'21–40 eggs' }, { l:'Incubation', v:'60–90 days' }, { l:'Nest builder', v:'Yes (unique)' }],
    funFacts: [
      { icon:'🏠', text:'The King Cobra is the <strong>only snake in the world that builds a nest</strong> — an elaborate mound of leaves and debris — and actively guards it.' },
      { icon:'🔊', text:'Its warning "hiss" is actually a low <strong>growl around 600 Hz</strong> — far lower than other snakes. Close up, it is genuinely terrifying.' },
      { icon:'🐍', text:'King cobras are <strong>immune to the venom of most snakes</strong> they eat, including other elapids.' },
      { icon:'💀', text:'A single bite delivers enough venom to <strong>kill an adult Asian elephant</strong>.' },
    ],
    attrs: [{ lbl:'Venomous', cls:'#7f1d1d' }, { lbl:'Apex Predator', cls:'#6d28d9' }, { lbl:'Oviparous', cls:'#0f766e' }, { lbl:'Solitary', cls:'#14532d' }],
    threats: ['Deforestation and habitat fragmentation in Western Ghats', 'Collection for traditional medicine and snake charming', 'Road kills on forest roads'],
    range: ['Western Ghats (Karnataka/Kerala)', 'Assam & Northeast India', 'Andaman Islands', 'Southeast Asia'],
    related: ['gharial', 'tiger', 'peacock', 'banyan'],
    sizeH: 30, sizeType: 'snake', sound: 'kingcobra',
  },

  rhino: {
    id: 'rhino', icon: '🦏', name: 'Indian Rhinoceros', sci: 'Rhinoceros unicornis',
    status: 'VU', statusLabel: 'Vulnerable', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Greater_one-horned_rhino.jpg/1280px-Greater_one-horned_rhino.jpg',
    heroGrad: 'linear-gradient(140deg,#100e08,#282010,#4a3c18)',
    iucn: 'VU', popTrend: 'Increasing', popNum: '~4,014 wild',
    popWhere: 'India (Kaziranga 70%+, Manas), Nepal',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Perissodactyla', Family:'Rhinocerotidae', Genus:'Rhinoceros', Species:'R. unicornis' },
    stats: [
      { l:'Population', v:'~4,014', u:'wild' },
      { l:'Lifespan', v:'35–45', u:'years' },
      { l:'Top Speed', v:'55', u:'km/h' },
      { l:'Weight', v:'2,200', u:'kg avg' },
      { l:'Horn length', v:'20–90', u:'cm' }
    ],
    about: 'A spectacular conservation success story. From fewer than 200 animals at the start of the 20th century — hunted nearly to extinction for their horn — the Indian One-Horned Rhino has recovered to over 4,000 today, largely through rigorous protection in Kaziranga National Park, Assam. The rhino\'s single horn is pure compressed keratin — the same protein as your fingernails.',
    diet: [{ label:'Grass', pct:65, color:'#3d7a4f' }, { label:'Leaves & bark', pct:20, color:'#52a669' }, { label:'Aquatic plants', pct:10, color:'#3a7fa8' }, { label:'Fruit', pct:5, color:'#c8922a' }],
    habitat: 'Alluvial floodplain grasslands — the tall "elephant grass" of Assam and the Terai of Nepal. Requires water for regular wallowing. Kaziranga National Park holds nearly 70% of the entire species population.',
    behavior: 'Mostly solitary except for mothers with calves. Males hold territories aggressively. Excellent swimmers. Poor eyesight but outstanding hearing and smell.',
    mating: [{ l:'Season', v:'Year-round' }, { l:'Gestation', v:'15–16 months' }, { l:'Birth weight', v:'~65 kg' }, { l:'Weaning', v:'2 years' }],
    funFacts: [
      { icon:'🔑', text:'The rhino\'s horn is <strong>entirely made of keratin</strong> — the same protein in your hair and nails — not bone. It grows back if lost.' },
      { icon:'🏊', text:'Indian rhinos are <strong>excellent swimmers</strong> and can swim across the Brahmaputra, which floods seasonally and can be kilometres wide.' },
      { icon:'🦺', text:'The rhino\'s thick "armour-plated" skin has <strong>deep folds</strong> that function like a biological suit of armour, while still allowing flexibility.' },
      { icon:'📈', text:'Indian rhino numbers have grown from <strong>200 in 1900 to 4,000+ today</strong> — one of conservation\'s greatest success stories.' },
    ],
    attrs: [{ lbl:'Herbivore', cls:'#14532d' }, { lbl:'Semi-aquatic', cls:'#1e3a5f' }, { lbl:'Grazer', cls:'#14532d' }, { lbl:'Solitary', cls:'#374151' }],
    threats: ['Poaching for horn (used in traditional medicine)', 'Habitat loss to agriculture around park edges', 'Flooding from climate change altering grassland structure'],
    range: ['Kaziranga NP, Assam (primary stronghold)', 'Manas NP, Assam', 'Orang NP, Assam', 'Chitwan NP, Nepal'],
    related: ['elephant', 'gaur', 'tiger', 'chital'],
    sizeH: 170, sizeType: 'rhino', sound: 'rhino',
  },

  gaur: {
    id: 'gaur', icon: '🐃', name: 'Indian Gaur', sci: 'Bos gaurus',
    status: 'VU', statusLabel: 'Vulnerable', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Gaur_bos_gaurus.jpg/1280px-Gaur_bos_gaurus.jpg',
    heroGrad: 'linear-gradient(140deg,#0e0a05,#20140a,#3a2010)',
    iucn: 'VU', popTrend: 'Decreasing', popNum: '~21,000 wild',
    popWhere: 'India (Western & Eastern Ghats), SE Asia',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Artiodactyla', Family:'Bovidae', Genus:'Bos', Species:'B. gaurus' },
    stats: [
      { l:'Population', v:'~21,000', u:'wild' },
      { l:'Lifespan', v:'24–30', u:'years' },
      { l:'Top Speed', v:'50', u:'km/h' },
      { l:'Weight', v:'800', u:'kg avg' },
      { l:'Shoulder ht.', v:'190', u:'cm' }
    ],
    about: 'The world\'s largest wild bovine. Adult males can reach 2.2 metres at the shoulder and weigh over a tonne — yet despite their formidable size, gaur are shy forest dwellers that will flee from human contact. The adult male is dark chocolate to black with striking white "stocking" legs up to the knee.',
    diet: [{ label:'Grass', pct:55, color:'#3d7a4f' }, { label:'Leaves', pct:25, color:'#52a669' }, { label:'Bark', pct:12, color:'#c8922a' }, { label:'Fruits', pct:8, color:'#e8b04a' }],
    habitat: 'Dense moist deciduous and semi-evergreen forests with access to open clearings for grazing. Key habitats: Nagarhole, Bandipur, Mudumalai (South India) and Kanha, Pench (Central India).',
    behavior: 'Lives in herds of 5–30, led by a dominant cow. Bulls may be solitary or form small bachelor groups. Highly alert to predators. Most active in early morning and late afternoon.',
    mating: [{ l:'Season', v:'Dec–May' }, { l:'Gestation', v:'275 days' }, { l:'Birth weight', v:'~23 kg' }, { l:'Weaning', v:'7–9 months' }],
    funFacts: [
      { icon:'🦵', text:'The gaur\'s distinctive <strong>white "stocking" legs</strong> below the knee are a key identification feature — no other bovine has this pattern.' },
      { icon:'🏔️', text:'Despite being the world\'s largest bovine, gaur can <strong>run at 50 km/h</strong> and are agile enough to jump over a 2-metre fence.' },
      { icon:'🌡️', text:'The prominent muscular ridge on the gaur\'s back — the <strong>dorsal ridge</strong> — can be 8–10 cm high and is used in dominance displays.' },
      { icon:'🤝', text:'Gaur often <strong>associate with deer and monkeys</strong> who alert them to predators, creating a multi-species early-warning system.' },
    ],
    attrs: [{ lbl:'Herbivore', cls:'#14532d' }, { lbl:'Diurnal', cls:'#78350f' }, { lbl:'Social', cls:'#1e3a5f' }, { lbl:'Grazer', cls:'#14532d' }],
    threats: ['Foot-and-mouth disease from domestic cattle', 'Hunting for meat and trophy (outside India)', 'Habitat loss to agriculture'],
    range: ['Western Ghats (Nagarhole, Bandipur)', 'Eastern Ghats', 'Kanha, Pench, Bandhavgarh (Central India)'],
    related: ['elephant', 'rhino', 'tiger', 'chital'],
    sizeH: 190, sizeType: 'quadruped', sound: 'gaur',
  },

  chital: {
    id: 'chital', icon: '🦌', name: 'Spotted Deer (Chital)', sci: 'Axis axis',
    status: 'LC', statusLabel: 'Least Concern', category: 'mammals',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Chital_male_2.jpg/1280px-Chital_male_2.jpg',
    heroGrad: 'linear-gradient(140deg,#0a1005,#18220a,#304010)',
    iucn: 'LC', popTrend: 'Stable', popNum: '100,000+ wild',
    popWhere: 'Indian Subcontinent, Sri Lanka',
    taxonomy: { Kingdom:'Animalia', Phylum:'Chordata', Class:'Mammalia', Order:'Artiodactyla', Family:'Cervidae', Genus:'Axis', Species:'A. axis' },
    stats: [
      { l:'Population', v:'>100,000', u:'wild' },
      { l:'Lifespan', v:'8–14', u:'years' },
      { l:'Top Speed', v:'65', u:'km/h' },
      { l:'Weight', v:'55', u:'kg avg' },
      { l:'Shoulder ht.', v:'90', u:'cm' }
    ],
    about: 'India\'s most abundant large deer, the Chital retains its white spots into adulthood — unlike most deer species, which lose spots after the fawn stage. They live in herds of 10–30 animals and share a remarkable mutualistic relationship with Hanuman langur monkeys: langurs drop fruits from trees for deer below, while deer alert langurs to ground predators.',
    diet: [{ label:'Grass', pct:60, color:'#3d7a4f' }, { label:'Leaves', pct:25, color:'#52a669' }, { label:'Fruits', pct:12, color:'#c8922a' }, { label:'Bark', pct:3, color:'#e8b04a' }],
    habitat: 'Deciduous forests, forest edges, and grassy glades across peninsular and northern India. Prefers dry deciduous and mixed forests with access to water.',
    behavior: 'Social and diurnal. Males grow and shed antlers annually. The alarm call — a sharp bark — alerts all species in the vicinity. Primary prey of tigers and leopards in most Indian forests.',
    mating: [{ l:'Season', v:'Year-round' }, { l:'Gestation', v:'210–225 days' }, { l:'Fawn size', v:'1–2' }, { l:'Fawn type', v:'Precocial' }],
    funFacts: [
      { icon:'🐒', text:'Chital and <strong>Hanuman langurs team up as a cross-species alarm system</strong>. Langurs spot aerial threats from trees; chital warn of ground predators.' },
      { icon:'⭐', text:'Unlike most deer, chital <strong>keep their white spots for life</strong>. These spots break up body outline in dappled forest light — perfect camouflage.' },
      { icon:'🦌', text:'A male chital\'s <strong>antlers take 3 months to grow</strong> and can reach 90 cm. Growing antler bone is the fastest-growing tissue in any mammal.' },
      { icon:'🌙', text:'Chital have no fixed breeding season — herds can contain males with <strong>hard antlers, velvet, and shed antlers simultaneously</strong>.' },
    ],
    attrs: [{ lbl:'Herbivore', cls:'#14532d' }, { lbl:'Diurnal', cls:'#78350f' }, { lbl:'Social', cls:'#1e3a5f' }, { lbl:'Precocial', cls:'#14532d' }],
    threats: ['Poaching for meat and antler velvet', 'Habitat degradation and overgrazing by livestock', 'Natural predation by tigers and leopards'],
    range: ['Pan-India below 1,000m', 'Sri Lanka', 'Terai grasslands (Nepal borders)'],
    related: ['tiger', 'elephant', 'gaur', 'rhino'],
    sizeH: 90, sizeType: 'quadruped', sound: 'chital',
  },

  banyan: {
    id: 'banyan', icon: '🌳', name: 'Banyan Tree', sci: 'Ficus benghalensis',
    status: 'LC', statusLabel: 'Least Concern', category: 'trees',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Ficus_benghalensis_-_Great_Banyan.jpg/1280px-Ficus_benghalensis_-_Great_Banyan.jpg',
    heroGrad: 'linear-gradient(140deg,#050e08,#0d2014,#1a4020)',
    iucn: 'LC', popTrend: 'Stable', popNum: 'Widespread — national tree of India',
    popWhere: 'Indian Subcontinent, Sri Lanka, Bangladesh, Pakistan',
    taxonomy: { Kingdom:'Plantae', Phylum:'Tracheophyta', Class:'Magnoliopsida', Order:'Rosales', Family:'Moraceae', Genus:'Ficus', Species:'F. benghalensis' },
    stats: [
      { l:'Max spread', v:'3.5', u:'acres' },
      { l:'Lifespan', v:'200–500+', u:'years' },
      { l:'Height', v:'20–30', u:'m' },
      { l:'Aerial roots', v:'3,800+', u:'recorded' },
      { l:'Status', v:'National', u:'Tree of India' }
    ],
    about: 'India\'s National Tree. A strangler fig by nature, the Banyan begins its life as a tiny seed deposited by birds in the canopy of another tree. As it grows, it sends aerial roots down to the ground; these thicken into new trunks, allowing a single tree to expand indefinitely. The Great Banyan in Kolkata\'s Acharya Jagadish Chandra Bose Indian Botanic Garden covers 3.5 acres with over 3,800 aerial roots — the widest tree in the world.',
    diet: [{ label:'Photosynthesis', pct:100, color:'#3d7a4f' }],
    habitat: 'Tropical and subtropical forests, roadsides, temple grounds, and village commons across the Indian subcontinent. The tree supports extraordinary biodiversity — hundreds of animal species depend on its figs.',
    behavior: 'Hemiepiphytic — begins life on another tree but becomes free-standing. The banyan-wasp relationship is ancient and exquisitely co-evolved: each Ficus species has its own exclusive fig wasp pollinator.',
    mating: [{ l:'Pollinator', v:'Fig wasp' }, { l:'Fruit type', v:'Syconium fig' }, { l:'Dispersal', v:'Birds & bats' }, { l:'Germination', v:'On host tree' }],
    funFacts: [
      { icon:'🌍', text:'The Great Banyan in Kolkata — a <strong>single tree</strong> — covers 3.5 acres and looks like an entire forest. It has over 3,800 aerial roots acting as trunks.' },
      { icon:'🐝', text:'Each Ficus species has a <strong>dedicated fig wasp pollinator</strong> — an evolutionary partnership 90 million years old.' },
      { icon:'🕌', text:'The word <strong>"banian" came to English</strong> from the Hindu merchants (banias) who traded under these trees. Portuguese sailors adopted it in the 16th century.' },
      { icon:'🌱', text:'A banyan starts as a <strong>strangler</strong> — seeds germinate in a host tree\'s canopy. The banyan\'s roots eventually surround and engulf the host, which dies.' },
    ],
    attrs: [{ lbl:'Evergreen', cls:'#14532d' }, { lbl:'Sacred', cls:'#78350f' }, { lbl:'National Tree', cls:'#7f1d1d' }],
    threats: ['Urban development cutting roots and compacting soil', 'Air and water pollution', 'Construction damage to root systems near roads'],
    range: ['Pan-India (below 1,200m)', 'Sri Lanka', 'Bangladesh', 'Pakistan (Sindh, Punjab)'],
    related: ['peepal', 'bamboo', 'peacock', 'kingcobra'],
    sizeH: 2800, sizeType: 'tree', sound: 'forest',
  },

  peepal: {
    id: 'peepal', icon: '🌳', name: 'Peepal Tree', sci: 'Ficus religiosa',
    status: 'LC', statusLabel: 'Least Concern', category: 'trees',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Ficus_religiosa.jpg/1280px-Ficus_religiosa.jpg',
    heroGrad: 'linear-gradient(140deg,#051005,#0a2010,#183020)',
    iucn: 'LC', popTrend: 'Stable', popNum: 'Widely cultivated, self-propagating',
    popWhere: 'Indian Subcontinent, Southeast Asia',
    taxonomy: { Kingdom:'Plantae', Phylum:'Tracheophyta', Class:'Magnoliopsida', Order:'Rosales', Family:'Moraceae', Genus:'Ficus', Species:'F. religiosa' },
    stats: [
      { l:'Lifespan', v:'1,000+', u:'years' },
      { l:'Height', v:'15–25', u:'m' },
      { l:'O₂ cycle', v:'24-hr', u:'continuous' },
      { l:'Sacred to', v:'3', u:'religions' },
      { l:'Status', v:'Sacred', u:'Tree' }
    ],
    about: 'Venerated by Hindus, Buddhists and Jains alike. The Buddha attained enlightenment beneath a Peepal at Bodh Gaya (the original tree\'s lineage is maintained to this day). Botanically remarkable: it performs Crassulacean Acid Metabolism (CAM), releasing oxygen around the clock — unique among trees. Its heart-shaped leaves with a long drip-tip tremble in the slightest breeze, earning it mystical associations in Indian culture.',
    diet: [{ label:'Photosynthesis (CAM)', pct:100, color:'#3d7a4f' }],
    habitat: 'Roadsides, temples, village centres, river banks and secondary forests. Found from the Himalayas down to Sri Lanka and across Southeast Asia.',
    behavior: 'Semi-epiphytic — often begins growth in cracks in walls, rocks or other trees. CAM photosynthesis means the tree opens its stomata at night, allowing continuous oxygen production. Can live over 1,000 years.',
    mating: [{ l:'Pollinator', v:'Fig wasp' }, { l:'Fruit type', v:'Fig syconium' }, { l:'Dispersal', v:'Birds, bats, monkeys' }, { l:'Sacred site', v:'Bodh Gaya' }],
    funFacts: [
      { icon:'🌬️', text:'Peepal is the <strong>only tree that produces oxygen 24 hours a day</strong> using CAM photosynthesis — an adaptation to water-stressed environments.' },
      { icon:'🙏', text:'A Peepal sapling from the <strong>original Bodh Gaya tree</strong> was sent to Sri Lanka in 288 BCE. Descendants still grow there.' },
      { icon:'💚', text:'The Peepal\'s <strong>distinctive trembling leaves</strong> are caused by long, flattened petioles (stalks). In Indian tradition, this trembling represents the omnipresence of the divine.' },
      { icon:'🌡️', text:'Peepal trees <strong>cool the surrounding air temperature</strong> by 3–5°C through transpiration, functioning as natural air conditioners in Indian villages.' },
    ],
    attrs: [{ lbl:'Sacred', cls:'#78350f' }, { lbl:'Evergreen', cls:'#14532d' }, { lbl:'24-hr O₂', cls:'#0f766e' }],
    threats: ['Urban construction damaging root systems', 'Pollution reducing lifespan and vigor', 'Cutting for firewood and timber'],
    range: ['Pan-India', 'Sri Lanka (sacred Bodh Gaya lineage)', 'Nepal', 'Southeast Asia (introduced)'],
    related: ['banyan', 'bamboo', 'kingcobra', 'peacock'],
    sizeH: 2500, sizeType: 'tree', sound: 'forest',
  },

  bamboo: {
    id: 'bamboo', icon: '🎋', name: 'Indian Bamboo', sci: 'Bambusoideae spp.',
    status: 'LC', statusLabel: 'Various species', category: 'trees',
    photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Bamboo_in_Sagano_Bamboo_Forest.jpg/1280px-Bamboo_in_Sagano_Bamboo_Forest.jpg',
    heroGrad: 'linear-gradient(140deg,#051008,#0a2010,#152a18)',
    iucn: 'LC', popTrend: 'Stable', popNum: '~136 species in India alone',
    popWhere: 'India (especially NE), Southeast Asia, globally',
    taxonomy: { Kingdom:'Plantae', Phylum:'Tracheophyta', Class:'Liliopsida', Order:'Poales', Family:'Poaceae', Genus:'Multiple', Species:'~136 spp. in India' },
    stats: [
      { l:'India species', v:'136+', u:'documented' },
      { l:'Max growth', v:'91', u:'cm / day' },
      { l:'Max height', v:'30', u:'m' },
      { l:'Flower cycle', v:'15–120', u:'years' },
      { l:'Strength', v:'Higher', u:'than mild steel' }
    ],
    about: 'Bamboo is technically a grass — yet it outgrows, outstrengths, and outlasts most wood. Certain Northeast Indian species grow 91 cm in a single day, making bamboo the fastest-growing plant on Earth. India has the world\'s second-highest bamboo diversity, with 136+ species.',
    diet: [{ label:'Photosynthesis', pct:100, color:'#3d7a4f' }],
    habitat: 'Tropical and subtropical forests, river banks, hill slopes, and monsoon forest edges across India. Especially abundant in Northeast India (Assam, Mizoram, Manipur, Meghalaya), the Western Ghats, and Andaman Islands.',
    behavior: 'Bamboo grows through "telescoping" — the culm emerges at its full diameter, then extends upward by elongating each internode. When a species flowers, all plants of that species worldwide flower simultaneously, then die.',
    mating: [{ l:'Flowering', v:'Mast seeding' }, { l:'Cycle', v:'15–120 years' }, { l:'Post-flower', v:'Mass die-off' }, { l:'Regrowth', v:'From seeds' }],
    funFacts: [
      { icon:'⚡', text:'Bamboo\'s <strong>tensile strength exceeds mild steel</strong> by weight. It\'s used to scaffold buildings in Hong Kong and as structural reinforcement across Asia.' },
      { icon:'🐼', text:'The <strong>giant panda\'s entire diet</strong> is bamboo — 12–38 kg per day. Their "false thumb" is actually an enlarged wrist bone adapted for grasping bamboo stems.' },
      { icon:'🐀', text:'When bamboo flowers in Mizoram every 48 years, the seeds fuel a <strong>rat population explosion</strong> ("mautam") that historically caused regional famines.' },
      { icon:'🌱', text:'Bamboo <strong>regenerates without replanting</strong> after harvesting — the roots remain and shoot new culms immediately.' },
    ],
    attrs: [{ lbl:'Grass family', cls:'#14532d' }, { lbl:'Fastest growing', cls:'#78350f' }, { lbl:'Ecological keystone', cls:'#1e3a5f' }],
    threats: ['Overextraction for paper and construction', 'Flowering die-off events (natural but impactful)', 'Habitat conversion to agriculture'],
    range: ['Northeast India (Assam, Mizoram, Meghalaya)', 'Western Ghats', 'Andaman Islands'],
    related: ['banyan', 'peepal', 'tiger', 'elephant'],
    sizeH: 3000, sizeType: 'bamboo', sound: 'forest',
  },
};

// Mosaic data for hero (species with best photos for mosaic)
const MOSAIC_SPECIES = [
  { id:'tiger', span: 'large' },
  { id:'peacock', span: '' },
  { id:'snowleopard', span: '' },
  { id:'elephant', span: '' },
  { id:'gharial', span: '' },
  { id:'chital', span: 'large' },
  { id:'kingcobra', span: '' },
  { id:'rhino', span: '' },
];

// A-Z data
const AZ_DATA = {
  A: [{ n:'Areca Palm', sci:'Areca catechu', cat:'Palm Tree' }, { n:'Asian Elephant', sci:'Elephas maximus', cat:'Mammal', id:'elephant' }, { n:'Ashoka Tree', sci:'Saraca asoca', cat:'Sacred Tree' }, { n:'Asiatic Lion', sci:'Panthera leo persica', cat:'Mammal' }],
  B: [{ n:'Banyan Tree', sci:'Ficus benghalensis', cat:'National Tree', id:'banyan' }, { n:'Bamboo', sci:'Bambusoideae spp.', cat:'Grass/Tree', id:'bamboo' }, { n:'Bengal Tiger', sci:'Panthera tigris tigris', cat:'Mammal', id:'tiger' }, { n:'Brahminy Kite', sci:'Haliastur indus', cat:'Bird' }],
  C: [{ n:'Chital (Spotted Deer)', sci:'Axis axis', cat:'Mammal', id:'chital' }, { n:'Coconut Palm', sci:'Cocos nucifera', cat:'Palm' }, { n:'Common Kingfisher', sci:'Alcedo atthis', cat:'Bird' }, { n:'Crested Porcupine', sci:'Hystrix indica', cat:'Mammal' }],
  D: [{ n:'Deodar Cedar', sci:'Cedrus deodara', cat:'Conifer' }, { n:'Dhole (Wild Dog)', sci:'Cuon alpinus', cat:'Mammal' }, { n:'Drongo', sci:'Dicrurus macrocercus', cat:'Bird' }],
  E: [{ n:'Asian Elephant', sci:'Elephas maximus', cat:'Mammal', id:'elephant' }],
  F: [{ n:'Flamingo (Lesser)', sci:'Phoeniconaias minor', cat:'Bird' }, { n:'Flying Lizard', sci:'Draco volans', cat:'Reptile' }],
  G: [{ n:'Gaur (Indian Bison)', sci:'Bos gaurus', cat:'Mammal', id:'gaur' }, { n:'Gharial', sci:'Gavialis gangeticus', cat:'Reptile', id:'gharial' }, { n:'Great Indian Bustard', sci:'Ardeotis nigriceps', cat:'Bird' }],
  H: [{ n:'Himalayan Black Bear', sci:'Ursus thibetanus', cat:'Mammal' }, { n:'Hoopoe', sci:'Upupa epops', cat:'Bird' }],
  I: [{ n:'Indian Peacock', sci:'Pavo cristatus', cat:'National Bird', id:'peacock' }, { n:'Indian Rhino', sci:'Rhinoceros unicornis', cat:'Mammal', id:'rhino' }, { n:'Indian Roller', sci:'Coracias benghalensis', cat:'Bird' }],
  J: [{ n:'Jamun', sci:'Syzygium cumini', cat:'Deciduous Tree' }, { n:'Jungle Cat', sci:'Felis chaus', cat:'Mammal' }],
  K: [{ n:'King Cobra', sci:'Ophiophagus hannah', cat:'Reptile', id:'kingcobra' }, { n:'Koel', sci:'Eudynamys scolopaceus', cat:'Bird' }],
  L: [{ n:'Leopard', sci:'Panthera pardus', cat:'Mammal' }, { n:'Lion-tailed Macaque', sci:'Macaca silenus', cat:'Mammal' }],
  M: [{ n:'Mango Tree', sci:'Mangifera indica', cat:'National Fruit Tree' }, { n:'Mugger Crocodile', sci:'Crocodylus palustris', cat:'Reptile' }],
  N: [{ n:'Neem Tree', sci:'Azadirachta indica', cat:'Medicinal Tree' }, { n:'Nilgai', sci:'Boselaphus tragocamelus', cat:'Mammal' }],
  O: [{ n:'One-Horned Rhinoceros', sci:'Rhinoceros unicornis', cat:'Mammal', id:'rhino' }],
  P: [{ n:'Peepal Tree', sci:'Ficus religiosa', cat:'Sacred Tree', id:'peepal' }, { n:'Painted Stork', sci:'Mycteria leucocephala', cat:'Bird' }, { n:'Pangolin', sci:'Manis crassicaudata', cat:'Mammal' }],
  Q: [{ n:'Quail (Common)', sci:'Coturnix coturnix', cat:'Bird' }],
  R: [{ n:'Red Panda', sci:'Ailurus fulgens', cat:'Mammal' }, { n:'River Tern', sci:'Sterna aurantia', cat:'Bird' }],
  S: [{ n:'Snow Leopard', sci:'Panthera uncia', cat:'Mammal', id:'snowleopard' }, { n:'Sal Tree', sci:'Shorea robusta', cat:'Deciduous Tree' }, { n:'Sarus Crane', sci:'Antigone antigone', cat:'Bird' }],
  T: [{ n:'Bengal Tiger', sci:'Panthera tigris tigris', cat:'Mammal', id:'tiger' }, { n:'Teak', sci:'Tectona grandis', cat:'Timber Tree' }],
  U: [{ n:'Urial', sci:'Ovis vignei', cat:'Mammal' }],
  V: [{ n:'Vulture (Indian)', sci:'Gyps indicus', cat:'Bird' }],
  W: [{ n:'Wild Ass (Indian)', sci:'Equus hemionus', cat:'Mammal' }, { n:'Wolf (Indian)', sci:'Canis lupus pallipes', cat:'Mammal' }],
  X: [],
  Y: [{ n:'Yellow Monitor', sci:'Varanus flavescens', cat:'Reptile' }],
  Z: [{ n:'Zebu', sci:'Bos taurus indicus', cat:'Domestic Bovine' }],
};

// Ticker facts
const TICKER_FACTS = [
  'India shelters over 75% of the world\'s wild tiger population — 4,500+ animals',
  'The Great Banyan in Kolkata covers 3.5 acres and is the widest tree on Earth',
  'Peepal tree releases oxygen 24 hours a day — unique among all trees worldwide',
  'The Indian Peacock\'s "tail" is actually its upper tail covert feathers — not a tail at all',
  'Asian elephants detect seismic rumbles from 30 km away through their feet and trunk',
  'Bamboo grows 91 cm in a single day — the fastest growing plant on Earth',
  'India has 1,300+ butterfly species — more than all of Europe combined',
  'The Gharial\'s narrow snout has 100+ sharp teeth perfectly shaped for catching fish',
  'Snow leopards cannot roar — they produce a unique "chuffle" sound found in no other cat',
  'The King Cobra is the only snake that builds a nest and guards its eggs',
];

// Collections
const COLLECTIONS = [
  { name:'Critically Endangered', count:'18 Species', photo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Female_gharial_%28Gavialis_gangeticus%29.jpg/800px-Female_gharial_%28Gavialis_gangeticus%29.jpg', cat:'reptiles' },
  { name:'Big Cats of India', count:'5 Species', photo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tiger_in_Ranthambhore.jpg/800px-Tiger_in_Ranthambhore.jpg', cat:'mammals' },
  { name:'Sacred Trees & Plants', count:'24 Species', photo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Ficus_benghalensis_-_Great_Banyan.jpg/800px-Ficus_benghalensis_-_Great_Banyan.jpg', cat:'trees' },
  { name:'Himalayan Species', count:'62 Species', photo:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Schneeleopard-schneeleopard.jpg/800px-Schneeleopard-schneeleopard.jpg', cat:'mammals' },
];
